version: "3.9"

services:

  memberservice:
    container_name: memberservice
    build:
      context: ./memberservice
    image: francescoxx/node_live_app
    ports:
      - "3002:3002"
    environment:
      - PG_DB=librairie
      - PG_USER=francesco
      - PG_PASSWORD=12345
      - PG_HOST=node_database
    depends_on:
      - node_database
    command: node app.js
      
  node_database:
    container_name: node_database
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=librairie
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data
      
volumes:
  node_db_data: {}